name: CI-CD-TEMPLATE-BUILDER-LOCAL
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ACTOR: saman-core
  IMAGE_APP_NAME: hierarchy

jobs:
  build_contenizer:
    name: Build & Contenerize App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'mandrel'
          github-token: ${{ secrets.GIT_TOKEN }}
          native-image-job-reports: 'true'
          version: '23.1.4.0-Final'

      - name: Build native app
        run: |
          ./mvnw clean install
          ./mvnw -pl app package -Pnative -DskipTests

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Container job build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./job/src/main/docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_APP_NAME }}-job:${{ github.sha }}

      - name: Container app build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./app/src/main/docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_APP_NAME }}:${{ github.sha }}
